language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer install --prefer-dist
    - mkdir -p build/logs

script:
    - bin/phpunit --coverage-clover build/logs/clover.cov

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.cov
